//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Git.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int id_deta { get; set; }
        public int id_prod_deta { get; set; }
        public string cantidad_deta { get; set; }
        public decimal costo_deta { get; set; }
        public bool existencia_deta { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
