//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_prod { get; set; }
        public string nombre_prod { get; set; }
        public int id_marca_prod { get; set; }
        public int id_grup_prod { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
